
[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
dynamic_padding = false
decorations = "none"

[scrolling]
history = 1000
multiplier = 3

[font]
size = 13.0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
